[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { version = "0.1.0", path = "../common" }
lazy_static = "1.4.0"
core_affinity = "0.8.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.139"