[package]
name = "recorder"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { version = "0.1.0", path = "../common" }
tokio = { version = "1.48.0", features = ["full"] }
sqlx = { version = "0.9.0-alpha.1", features = ["runtime-tokio", "postgres"] }
anyhow = "1.0.100"