[package]
name = "market-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
common = { version = "0.1.0", path = "../common" }
core_affinity = "0.8.3"
dashmap = "6.1.0"
serde_json = "1.0.145"